# This YAML file must contains the configuration of each mesh to properly build the URDF automagically.
# The aim of this additional file is to encapsulate all the physical properties in a single place without hiding them
# in a long URDF structure.
#
# Note: there is no need to modify this file unless you hack the qbhand physical mechanism. Nonetheless it is
#       recommended to create a distinct YAML file for each version of the qbhand (this helps with versioning and
#       leaves the default configuration as is).
#
# Brief description:
# * The `default` group holds the anchors for the common default settings, i.e. avoid annoying repetitions.
# * The `qb_hand_<left/right>` group contains the current properties to build the URDF correctly.

## WORK IN PROGRESS: ALL NUMERIC VALUES ARE OLD VALUES FROM SOFT HAND RESEARCH!!!!!!

default:
  parameters:
    axis_abduction: &axis_abduction "0 0 -1"
    axis_flexion: &axis_flexion "0 0 -1"
    dynamics: &dynamics
      damping: 0.0
      friction: 0.0
    effort_limit: &effort 100
    velocity_limit: &velocity 100
    virtual_mechanism: &virtual_mechanism
      position: "0.013 0 0"
      orientation: "0 0 0"
    synergy: &synergy
      axis: "0 0 1"  # it is not important though
      dynamics: *dynamics
      limits:
        lower: 0.0
        upper: 1.0
        effort: *effort
        velocity: *velocity
    manipulation: &manipulation
      axis: "0 0 1"  # it is not important though
      dynamics: *dynamics
      limits:
        lower: -1.0
        upper: 1.0
        effort: *effort
        velocity: *velocity
    motor_1: &motor_1
      axis: "0 0 1"  # it is not important though
      dynamics: *dynamics
      limits:
        lower: 0
        upper: 1.0
        effort: *effort
        velocity: *velocity
    motor_2: &motor_2
      axis: "0 0 1"  # it is not important though
      dynamics: *dynamics
      limits:
        lower: 0
        upper: 1.0
        effort: *effort
        velocity: *velocity

  finger:
    knuckle_index: &knuckle_index
      mesh: "sh_ph_prx_inj_d9_l_urdf"
      mesh_collision: "sh_ph_prx_inj_d9_l_urdf"
      # 'position' and 'orientation' should be specified each time
      position: "0 0 0"
      orientation: "0 0 0"
      axis: *axis_abduction
      mimic_reduction: 0.0
      dynamics: *dynamics
      limits:
        lower: -0.524
        upper: 0.524
        effort: *effort
        velocity: *velocity
      inertial:
        mass: 0.0095  # 9.5g
        origin:
          position: "4.2753603e-04  0.0 -1.4321738e-03"  # y^ less than e-04 from CAD --> 1.6685384e-07
          orientation: "0 0 0"
        inertia:
          ixx: 6.4337303e-07
          ixy: 0.0  # less than e-09 from CAD --> -6.1071201e-12
          ixz: -3.9373913e-08
          iyy: 1.1253771e-06
          iyz: 0.0  # less than e-09 from CAD --> 1.0214952e-11
          izz: 7.2336948e-07

    knuckle_middle: &knuckle_middle
      mesh: "sh_ph_prx_inj_d9_m_urdf"
      mesh_collision: "sh_ph_prx_inj_d9_m_urdf"
      # 'position' and 'orientation' should be specified each time
      position: "0 0 0"
      orientation: "0 0 0"
      axis: *axis_abduction
      mimic_reduction: 0.0
      dynamics: *dynamics
      limits:
        lower: -0.524
        upper: 0.524
        effort: *effort
        velocity: *velocity
      inertial:
        mass: 0.0095  # 9.5g
        origin:
          position: "4.2753603e-04  0.0 -1.4321738e-03"  # y^ less than e-04 from CAD --> 1.6685384e-07
          orientation: "0 0 0"
        inertia:
          ixx: 6.4337303e-07
          ixy: 0.0  # less than e-09 from CAD --> -6.1071201e-12
          ixz: -3.9373913e-08
          iyy: 1.1253771e-06
          iyz: 0.0  # less than e-09 from CAD --> 1.0214952e-11
          izz: 7.2336948e-07

    knuckle_rs: &knuckle_rs
      mesh: "sh_ph_prx_inj_d9_r_urdf"
      mesh_collision: "sh_ph_prx_inj_d9_r_urdf"
      # 'position' and 'orientation' should be specified each time
      position: "0 0 0"
      orientation: "0 0 0"
      axis: *axis_abduction
      mimic_reduction: 0.0
      dynamics: *dynamics
      limits:
        lower: -0.524
        upper: 0.524
        effort: *effort
        velocity: *velocity
      inertial:
        mass: 0.0095  # 9.5g
        origin:
          position: "4.2753603e-04  0.0 -1.4321738e-03"  # y^ less than e-04 from CAD --> 1.6685384e-07
          orientation: "0 0 0"
        inertia:
          ixx: 6.4337303e-07
          ixy: 0.0  # less than e-09 from CAD --> -6.1071201e-12
          ixz: -3.9373913e-08
          iyy: 1.1253771e-06
          iyz: 0.0  # less than e-09 from CAD --> 1.0214952e-11
          izz: 7.2336948e-07

    knuckle_thumb_r: &knuckle_thumb_r
      mesh: "sh_ph_thumb_inj_d9_r_urdf"
      mesh_collision: "sh_ph_thumb_inj_d9_r_urdf"
      # 'position' and 'orientation' should be specified each time
      position: "0 0 0"
      orientation: "0 0 0"
      axis: *axis_abduction
      mimic_reduction: 2.542
      dynamics: *dynamics
      limits:
        lower: 0.0
        upper: 1.571
        effort: *effort
        velocity: *velocity
      inertial:
        mass: 0.0100  # 10.0g
        origin:
          position: "1.3071561e-02 -2.7357764e-03 6.4347823e-04"
          orientation: "0 0 0"
        inertia:
          ixx: 3.5865978e-07
          ixy: 2.0944224e-07
          ixz: -6.8657569e-08
          iyy: 1.3885564e-06
          iyz: 3.2170608e-08
          izz: 1.3571203e-06

    phalax_30: &phalax_30
      mesh: "mc_h_pad_30_urdf"
      mesh_collision: "mc_h_pad_30_urdf"
      position: "0.017 0 0"
      orientation: "0 0 0"
      axis: *axis_flexion
      mimic_reduction: 0.785
      virtual_mechanism: *virtual_mechanism
      dynamics: *dynamics
      limits:
        lower: 0.0
        upper: 0.785
        effort: *effort
        velocity: *velocity
      inertial:
        mass: 0.0082  # 8.2g
        origin:
          position: "8.7707437e-03 -1.7863138e-03 0.0"  # z^ less than e-04 from CAD --> -2.5774703e-05
          orientation: "0 0 0"
        inertia:
          ixx: 2.2722068e-07
          ixy: 1.1586053e-08
          ixz: 0.0  # less than e-09 from CAD --> -5.6391369e-11
          iyy: 5.5947233e-07
          iyz: 0.0  # less than e-09 from CAD --> 2.3431511e-11
          izz: 5.9562195e-07

    phalax_25: &phalax_25
      mesh: "mc_h_pad_25_urdf"
      mesh_collision: "mc_h_pad_25_urdf"
      position: "0.017 0 0"
      orientation: "0 0 0"
      axis: *axis_flexion
      mimic_reduction: 0.785
      virtual_mechanism: *virtual_mechanism
      dynamics: *dynamics
      limits:
        lower: 0.0
        upper: 0.785
        effort: *effort
        velocity: *velocity
      inertial:
        mass: 0.0082  # 8.2g
        origin:
          position: "8.7707437e-03 -1.7863138e-03 0.0"  # z^ less than e-04 from CAD --> -2.5774703e-05
          orientation: "0 0 0"
        inertia:
          ixx: 2.2722068e-07
          ixy: 1.1586053e-08
          ixz: 0.0  # less than e-09 from CAD --> -5.6391369e-11
          iyy: 5.5947233e-07
          iyz: 0.0  # less than e-09 from CAD --> 2.3431511e-11
          izz: 5.9562195e-07

    phalax_21: &phalax_21
      mesh: "mc_h_pad_21_urdf"
      mesh_collision: "mc_h_pad_21_urdf"
      position: "0.017 0 0"
      orientation: "0 0 0"
      axis: *axis_flexion
      mimic_reduction: 0.785
      virtual_mechanism: *virtual_mechanism
      dynamics: *dynamics
      limits:
        lower: 0.0
        upper: 0.785
        effort: *effort
        velocity: *velocity
      inertial:
        mass: 0.0082  # 8.2g
        origin:
          position: "8.7707437e-03 -1.7863138e-03 0.0"  # z^ less than e-04 from CAD --> -2.5774703e-05
          orientation: "0 0 0"
        inertia:
          ixx: 2.2722068e-07
          ixy: 1.1586053e-08
          ixz: 0.0  # less than e-09 from CAD --> -5.6391369e-11
          iyy: 5.5947233e-07
          iyz: 0.0  # less than e-09 from CAD --> 2.3431511e-11
          izz: 5.9562195e-07

    phalax_distal: &phalax_distal
      mesh: "mc_h_pad_dist_urdf"
      mesh_collision: "mc_h_pad_dist_urdf"
      position: "0.009 0 0"
      orientation: "0 0 0"
      axis: *axis_flexion
      mimic_reduction: 0.785
      virtual_mechanism: *virtual_mechanism
      dynamics: *dynamics
      limits:
        lower: 0.0
        upper: 0.785
        effort: *effort
        velocity: *velocity
      inertial:
        mass: 0.0090  # 9.0g
        origin:
          position: "8.8025467e-03 -1.7219289e-03 0.0"  # z^ less than e-04 from CAD --> -2.1350175e-07
          orientation: "0 0 0"
        inertia:
          ixx: 2.6586142e-07
          ixy: 1.2416847e-08
          ixz: 0.0  # less than e-09 from CAD --> -8.6698823e-12
          iyy: 5.9935767e-07
          iyz: 0.0  # less than e-09 from CAD --> -9.3832346e-12
          izz: 6.6781963e-07

qbshin_right:
  
  base:
    mesh: "shin_wrist_urdf"
    mesh_collision: "shin_wrist_urdf"
    position: "0.0 7.8738498e-04 1.5878899e-02"
    orientation: "0 0 0"
    inertial:
      mass: 0.450
      origin:
        position: "0.0030 -0.0449 0.0135"
        orientation: "0 0 0"
      inertia:  # all approx
        ixx: 0.00045
        ixy: 0.0
        ixz: 0.0
        iyy: 0.00060
        iyz: 0.0
        izz: 0.00025

  palm:
    mesh: "shin_frame_urdf"
    mesh_collision: "shin_frame_urdf"
    position: "-0.005 0.0 0.071"
    orientation: "1.57 0 0" # will be overrided from mobile flange
    inertial:
      mass: 0.450
      origin:
        position: "0.0030 -0.0449 -0.0135"
        orientation: "0 0 0"
      inertia:  # all approx
        ixx: 0.00045
        ixy: 0.0
        ixz: 0.0
        iyy: 0.00060
        iyz: 0.0
        izz: 0.00025

  synergy: *synergy
  manipulation: *manipulation
  motor_1: *motor_1
  motor_2: *motor_2

  # all fingers have the same base structure and only few things change among them (e.g. the pose of the knuckle)
  thumb:
    knuckle:
      << : *knuckle_thumb_r
      position: "-0.044 0.027 -0.03"
      orientation: "-1.57 3.5 -0.68"
    proximal:
      << : *phalax_30
      position: "0.02 -0.003 0"
      orientation: "-1.57 0.0 0.0"
    distal: 
      << : *phalax_distal
      position: "0.014 0.002 0"
      orientation: "0.0 0.0 0.0"

  index:
    knuckle:
      << : *knuckle_index
      position: "-0.032 0.062 -0.022"
      orientation: "1.57 0 1.57"
      mimic_reduction: -0.2
    proximal:      
      << : *phalax_30
      position: "0.01 0 0.002"
      orientation: "0.0 0.0 0.0"
    middle: *phalax_25
    distal: 
      << : *phalax_distal
      position: "0.012 0.002 0"
      orientation: "0.0 0.0 0.0"

  middle:
    knuckle:
      << : *knuckle_middle
      position: "-0.005 0.068 -0.022"
      orientation: "1.57 0 1.57"
      mimic_reduction: 0.0
    proximal:      
      << : *phalax_30
      position: "0.01 0 0"
      orientation: "0.0 0.0 0.0"
    middle: *phalax_30
    distal: 
      << : *phalax_distal
      position: "0.014 0.002 0"
      orientation: "0.0 0.0 0.0"

  ring:
    knuckle:
      << : *knuckle_rs
      position: "0.022 0.062 -0.022"
      orientation: "1.57 0 1.57"
      mimic_reduction: 0.2
    proximal:      
      << : *phalax_30
      position: "0.01 0 -0.002"
      orientation: "0.0 0.0 0.0"
    middle: *phalax_25
    distal: 
      << : *phalax_distal
      position: "0.012 0.002 0"
      orientation: "0.0 0.0 0.0"

  little:
    knuckle:
      << : *knuckle_rs
      position: "0.049 0.044 -0.022"
      orientation: "1.57 0 1.57"
      mimic_reduction: 0.4
    proximal:      
      << : *phalax_25
      position: "0.01 0 -0.002"
      orientation: "0.0 0.0 0.0"
    middle:      
      << : *phalax_21
      position: "0.01 0 0"
      orientation: "0.0 0.0 0.0"
    distal: 
      << : *phalax_distal
      position: "0.008 0.002 0"
      orientation: "0.0 0.0 0.0"
