controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    synergy_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

forward_position_controller:
  ros__parameters:
    interface_name: position
    joints:
      - qbshin_synergy_joint

synergy_trajectory_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - qbshin_synergy_joint
    constraints: # fake values due to the adaptability
      goal_time: 0.0
      stopped_velocity_tolerance: 0.0
      qbshin_synergy_joint: {trajectory: 0.0, goal: 0.0}
    interface_name: position
    state_publish_rate: 25.0
    action_monitor_rate: 10.0
    # open_loop_control: true   
    allow_integration_in_goal_trajectories: false
    deduce_states_from_derivatives: false